parameters:
    locale: en
    locales: [en, de]
    secret: 10784a86848b5412b5f7fa644e90ef24e
    database_driver: pdo_mysql
    database_path: null
    phpcr_backend:
        type: doctrinedbal
        connection: doctrine.dbal.default_connection
# Enable these lines to use file system caching for the storage API
#        caches:
#            meta: liip_doctrine_cache.ns.meta
#            nodes: liip_doctrine_cache.ns.nodes
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_pass: admin
    database_host: localhost
    database_port: null
    database_name: cmf
    database_user: root
    database_password: ""